import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import type { BillingPacket } from "./billing";

/**
 * The billing-day packet as a real PDF — the artifact the office prints,
 * files, and argues from. Same BillingPacket the CSV is built from, so the
 * two can never disagree. Section structure mirrors the billing page
 * (blockers → billable → missed runs → office backlog → to-enter → late).
 */

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 9, fontFamily: "Helvetica", color: "#1f2328" },
  title: { fontSize: 16, fontFamily: "Helvetica-Bold" },
  meta: { fontSize: 8, color: "#59636e", marginTop: 4 },
  cards: { flexDirection: "row", gap: 8, marginTop: 12 },
  card: { flexGrow: 1, borderWidth: 1, borderColor: "#d1d9e0", borderRadius: 4, padding: 8 },
  cardLabel: { fontSize: 6.5, color: "#59636e", textTransform: "uppercase", letterSpacing: 0.5 },
  cardValue: { fontSize: 13, fontFamily: "Helvetica-Bold", marginTop: 2 },
  section: { fontSize: 9, fontFamily: "Helvetica-Bold", marginTop: 14, marginBottom: 4, textTransform: "uppercase" },
  row: { flexDirection: "row", paddingVertical: 3, borderBottomWidth: 0.5, borderBottomColor: "#d1d9e0" },
  danger: { borderLeftWidth: 2, borderLeftColor: "#cf222e", paddingLeft: 6, marginBottom: 3 },
  move: { borderLeftWidth: 2, borderLeftColor: "#9a6700", paddingLeft: 6, marginBottom: 3 },
  detail: { flex: 1, paddingRight: 8 },
  ft: { fontFamily: "Helvetica-Bold", width: 70 },
  metaNote: { fontSize: 7, color: "#59636e", marginTop: 1 },
  footer: { position: "absolute", bottom: 24, left: 36, right: 36, fontSize: 7, color: "#59636e" },
});

const ft = (n: number) => n.toLocaleString("en-US");

const KIND_SECTIONS: { kinds: BillingPacket["rows"][number]["kind"][]; title: string }[] = [
  { kinds: ["footage", "over", "hole"], title: "Do not invoice without checking" },
  { kinds: ["to-enter"], title: "To enter / billable" },
  { kinds: ["late"], title: "Late entries & missed runs" },
];

export function BillingPacketPdf(props: { packet: BillingPacket; sheetTitle: string; sinceFtKnown: boolean }) {
  const p = props.packet;
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{props.sheetTitle}</Text>
        <Text style={styles.meta}>
          billing day · snapshot {p.snapshotLabel} · generated by SheetDiff — byte-identical for the same data
        </Text>

        <View style={styles.cards}>
          <View style={styles.card}>
            <Text style={styles.cardLabel}>placed since collection</Text>
            <Text style={styles.cardValue}>{props.sinceFtKnown ? `${ft(p.placedSinceFt)} ft` : "—"}</Text>
          </View>
          <View style={styles.card}>
            <Text style={styles.cardLabel}>open holes</Text>
            <Text style={styles.cardValue}>{ft(p.openHoleFt)} ft</Text>
          </View>
          <View style={styles.card}>
            <Text style={styles.cardLabel}>to enter</Text>
            <Text style={styles.cardValue}>{p.toEnterCount}</Text>
          </View>
          <View style={styles.card}>
            <Text style={styles.cardLabel}>late entries</Text>
            <Text style={styles.cardValue}>{p.lateCount}</Text>
          </View>
        </View>

        {KIND_SECTIONS.map((section) => {
          const rows = p.rows.filter((r) => section.kinds.includes(r.kind));
          if (rows.length === 0) return null;
          const danger = section.kinds.includes("hole") || section.kinds.includes("over");
          return (
            <View key={section.title} wrap={false}>
              <Text style={styles.section}>{section.title}</Text>
              {rows.map((r, i) => (
                <View key={i} style={danger ? styles.danger : styles.move} wrap={false}>
                  <View style={styles.row}>
                    <Text style={styles.detail}>{r.detail}</Text>
                    {r.ft !== undefined ? <Text style={styles.ft}>{ft(r.ft)} ft</Text> : null}
                  </View>
                  {r.meta ? <Text style={styles.metaNote}>{r.meta}</Text> : null}
                </View>
              ))}
            </View>
          );
        })}

        <Text style={styles.footer}>
          SheetDiff · placed footage since last collection · negative numbers are corrections/removals · holes are
          unbooked footage: do not invoice
        </Text>
      </Page>
    </Document>
  );
}
